<?php

/**
 * This file is part of the Texy! (https://texy.nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

declare(strict_types=1);

namespace Texy\Modules;

use Texy;
use Texy\Modifier;
use Texy\Nodes\HeadingNode;
use Texy\Nodes\HeadingType;
use Texy\ParseContext;
use Texy\Syntax;
use function array_flip, array_values, asort, max, min, rtrim, strlen, trim;


/**
 * Processes heading syntax (underlined and surrounded) and builds table of contents.
 */
final class HeadingModule extends Texy\Module
{
	public const
		DYNAMIC = 1, // auto-leveling
		FIXED = 2; // fixed-leveling

	/** textual content of first heading */
	public ?string $title = null;

	/** @var list<array{node: HeadingNode, title?: string}>  generated Table of Contents */
	public array $TOC = [];

	/** level of top heading, 1..6 */
	public int $top = 1;

	/** surrounded headings: more #### means higher heading */
	public bool $moreMeansHigher = true;

	/** balancing mode */
	public int $balancing = self::DYNAMIC;

	/** @var array<string, int>  when $balancing = HeadingModule::FIXED */
	public array $levels = [
		'#' => 0, // # --> $levels['#'] + $top = 0 + 1 = 1 --> <h1> ... </h1>
		'*' => 1,
		'=' => 2,
		'-' => 3,
	];

	/** generate ID for headings? */
	public bool $generateID = false;

	/** prefix for autogenerated IDs */
	public string $idPrefix = 'toc-';

	/** @var array<string, true>  used ID's */
	private array $usedID = [];


	public function __construct(
		private Texy\Texy $texy,
	) {
		$texy->addHandler('afterParse', $this->afterParse(...));
	}


	public function beforeParse(string &$text): void
	{
		$this->texy->registerBlockPattern(
			$this->parseUnderline(...),
			'~^
				( \S .{0,1000} )                 # heading text (1)
				' . Texy\Patterns::MODIFIER_H . '? # modifier (2)
				\n
				( \#{3,}+ | \*{3,}+ | ={3,}+ | -{3,}+ )  # underline characters (3)
			$~mU',
			Syntax::HeadingUnderlined,
		);

		$this->texy->registerBlockPattern(
			$this->parseSurround(...),
			'~^
				( \#{2,}+ | ={2,}+ )             # opening characters (1)
				(.+)                             # heading text (2)
				' . Texy\Patterns::MODIFIER_H . '? # modifier (2)
			$~mU',
			Syntax::HeadingSurrounded,
		);

		$this->title = null;
		$this->usedID = [];
		$this->TOC = [];
	}


	/**
	 * Post-process AST headings - apply balancing and calculate final levels.
	 */
	public function afterParse(Texy\Nodes\DocumentNode $document): void
	{
		// Collect all heading nodes (separated: dynamic balancing vs fixed balancing)
		[$dynamicHeadings, $fixedHeadings] = $this->collectHeadings($document);

		// Apply fixed balancing to texysource headings (just add top)
		foreach ($fixedHeadings as $node) {
			$node->level = min(6, max(1, $node->level + $this->top));
		}

		// Process main document headings
		$headings = $dynamicHeadings;
		if (!$headings) {
			// Still need to process ID generation for fixed headings
			$headings = $fixedHeadings;
			if (!$headings) {
				return;
			}
		} elseif ($this->balancing === self::DYNAMIC) {
			$map = [];
			$min = 100;

			// First pass: collect level information
			foreach ($headings as $node) {
				$level = $node->level;
				if ($node->type === HeadingType::Surrounded) {
					$min = min($level, $min);
				} elseif ($node->type === HeadingType::Underlined) {
					$map[$level] = $level;
				}
			}

			// Calculate top offset for surrounded headings
			$top = $this->top - $min;

			// Sort underlined levels and create mapping
			asort($map);
			$map = array_flip(array_values($map));

			// Second pass: apply calculated levels
			foreach ($headings as $node) {
				$level = match ($node->type) {
					HeadingType::Surrounded => $node->level + $top,
					HeadingType::Underlined => $map[$node->level] + $this->top,
				};
				$node->level = min(6, max(1, $level));
			}
		} else {
			// FIXED balancing - just add top
			foreach ($headings as $node) {
				$node->level = min(6, max(1, $node->level + $this->top));
			}
		}

		// Generate IDs if enabled (only for main document headings)
		if ($this->generateID) {
			foreach ($dynamicHeadings as $node) {
				// Check for custom TOC title in style
				$tocTitle = $node->modifier?->styles['toc'] ?? null;
				if ($tocTitle !== null) {
					unset($node->modifier->styles['toc']);
					$title = $tocTitle;
				} else {
					$title = trim(Texy\Helpers::extractText($node));
				}

				// Skip if ID already set in modifier
				if ($node->modifier?->id) {
					$this->usedID[$node->modifier->id] = true;

					continue;
				}

				$id = $this->idPrefix . Texy\Helpers::webalize($title);
				$counter = '';
				if (isset($this->usedID[$id . $counter])) {
					$counter = 2;
					while (isset($this->usedID[$id . '-' . $counter])) {
						$counter++;
					}

					$id .= '-' . $counter;
				}

				$this->usedID[$id] = true;

				// Create modifier if not exists
				if ($node->modifier === null) {
					$node->modifier = new Modifier;
				}

				$node->modifier->id = $id;

			}
		}

		// Set document title from first heading (main document only)
		if ($this->title === null && $dynamicHeadings) {
			$this->title = trim(Texy\Helpers::extractText($dynamicHeadings[0]));
		}

		// Build TOC (only for main document headings)
		foreach ($dynamicHeadings as $node) {
			$entry = ['node' => $node];
			if ($this->generateID) {
				$entry['title'] = trim(Texy\Helpers::extractText($node));
			}

			$this->TOC[] = $entry;
		}
	}


	/**
	 * Parses underlined heading.
	 * @param  array<?string>  $matches
	 */
	public function parseUnderline(ParseContext $context, array $matches): HeadingNode
	{
		[, $mContent, $mMod, $mLine] = $matches;
		$level = $this->levels[$mLine[0]];
		return new HeadingNode(
			$context->parseInline(trim($mContent)),
			$level,
			HeadingType::Underlined,
			Modifier::parse($mMod),
		);
	}


	/**
	 * Parses surrounded heading.
	 * @param  array<?string>  $matches
	 */
	public function parseSurround(ParseContext $context, array $matches): HeadingNode
	{
		[, $mLine, $mContent, $mMod] = $matches;
		$level = min(7, max(2, strlen($mLine)));
		$level = $this->moreMeansHigher ? 7 - $level : $level - 2;
		$mContent = rtrim($mContent, $mLine[0] . ' ');

		return new HeadingNode(
			$context->parseInline(trim($mContent)),
			$level,
			HeadingType::Surrounded,
			Modifier::parse($mMod),
		);
	}


	/**
	 * Collect all HeadingNode from AST.
	 * Headings inside texysource sections are collected separately (for fixed balancing).
	 * @return array{list<HeadingNode>, list<HeadingNode>}  [headings for dynamic balancing, headings for fixed balancing]
	 */
	private function collectHeadings(Texy\Node $node, bool $inTexysource = false): array
	{
		// Check if entering texysource section
		if ($node instanceof Texy\Nodes\SectionNode && $node->type === 'texysource') {
			$inTexysource = true;
		}

		$dynamic = [];
		$fixed = [];

		if ($node instanceof HeadingNode) {
			if ($inTexysource) {
				$fixed[] = $node;
			} else {
				$dynamic[] = $node;
			}
		}

		foreach ($node->getNodes() as $child) {
			[$childDynamic, $childFixed] = $this->collectHeadings($child, $inTexysource);
			$dynamic = [...$dynamic, ...$childDynamic];
			$fixed = [...$fixed, ...$childFixed];
		}

		return [$dynamic, $fixed];
	}
}
