<?php

/**
 * This file is part of the Texy! (https://texy.nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

declare(strict_types=1);

namespace Texy\Modules;

use Texy;
use Texy\Modifier;
use Texy\Nodes;
use Texy\Output\Html\Generator;
use Texy\Position;
use function array_flip, array_values, asort, max, min, rtrim, strlen, trim;


/**
 * Processes heading syntax (underlined and surrounded) and builds table of contents.
 */
final class HeadingModule extends Texy\Module
{
	public const
		DYNAMIC = 1, // auto-leveling
		FIXED = 2; // fixed-leveling

	/** textual content of first heading */
	public ?string $title = null;

	/** @var list<array{el: Texy\HtmlElement, level: int, type: string, title?: string}>  generated Table of Contents */
	public array $TOC = [];

	public bool $generateID = false;

	/** prefix for autogenerated ID */
	public string $idPrefix = 'toc-';

	/** level of top heading, 1..6 */
	public int $top = 1;

	/** surrounded headings: more #### means higher heading */
	public bool $moreMeansHigher = true;

	/** balancing mode */
	public int $balancing = self::DYNAMIC;

	/** @var array<string, int>  when $balancing = HeadingModule::FIXED */
	public array $levels = [
		'#' => 0, // # --> $levels['#'] + $top = 0 + 1 = 1 --> <h1> ... </h1>
		'*' => 1,
		'=' => 2,
		'-' => 3,
	];

	/** @var array<string, true>  used ID's */
	private array $usedID = [];


	public function __construct(
		private Texy\Texy $texy,
	) {
		$texy->addHandler('afterParse', $this->afterParse(...));
		$texy->htmlGenerator->registerHandler($this->solve(...));
	}


	public function beforeParse(string &$text): void
	{
		$this->texy->registerBlockPattern(
			$this->parseUnderline(...),
			'~^
				( \S .{0,1000} )                 # heading text (1)
				' . Texy\Patterns::MODIFIER_H . '? # modifier (2)
				\n
				( \#{3,}+ | \*{3,}+ | ={3,}+ | -{3,}+ )  # underline characters (3)
			$~mU',
			'heading/underlined',
		);

		$this->texy->registerBlockPattern(
			$this->parseSurround(...),
			'~^
				( \#{2,}+ | ={2,}+ )             # opening characters (1)
				(.+)                             # heading text (2)
				' . Texy\Patterns::MODIFIER_H . '? # modifier (2)
			$~mU',
			'heading/surrounded',
		);

		$this->title = null;
		$this->usedID = [];
		$this->TOC = [];
	}


	/**
	 * Post-process AST headings - apply balancing and calculate final levels.
	 */
	public function afterParse(Texy\Nodes\DocumentNode $document): void
	{
		// Collect all heading nodes
		$headings = $this->collectHeadings($document);
		if (!$headings) {
			return;
		}

		if ($this->balancing === self::DYNAMIC) {
			$map = [];
			$min = 100;

			// First pass: collect level information
			foreach ($headings as $node) {
				$level = $node->level;
				if ($node->type === Texy\Nodes\HeadingNode::Surrounded) {
					$min = min($level, $min);
				} elseif ($node->type === Texy\Nodes\HeadingNode::Underlined) {
					$map[$level] = $level;
				}
			}

			// Calculate top offset for surrounded headings
			$top = $this->top - $min;

			// Sort underlined levels and create mapping
			asort($map);
			$map = array_flip(array_values($map));

			// Second pass: apply calculated levels
			foreach ($headings as $node) {
				if ($node->type === Texy\Nodes\HeadingNode::Surrounded) {
					$level = $node->level + $top;
				} elseif ($node->type === Texy\Nodes\HeadingNode::Underlined) {
					$level = $map[$node->level] + $this->top;
				} else {
					$level = $node->level;
				}

				$node->level = min(6, max(1, $level));
			}
		} else {
			// FIXED balancing - just add top
			foreach ($headings as $node) {
				$node->level = min(6, max(1, $node->level + $this->top));
			}
		}

		// Generate IDs if enabled
		if ($this->generateID) {
			foreach ($headings as $node) {
				// Check for custom TOC title in style
				$tocTitle = $node->modifier?->styles['toc'] ?? null;
				if ($tocTitle !== null) {
					unset($node->modifier->styles['toc']);
					$title = $tocTitle;
				} else {
					$title = trim(Texy\Helpers::extractText($node));
				}

				// Skip if ID already set in modifier
				if ($node->modifier?->id) {
					$this->usedID[$node->modifier->id] = true;
					continue;
				}

				$id = $this->idPrefix . Texy\Helpers::webalize($title);
				$counter = '';
				if (isset($this->usedID[$id . $counter])) {
					$counter = 2;
					while (isset($this->usedID[$id . '-' . $counter])) {
						$counter++;
					}

					$id .= '-' . $counter;
				}

				$this->usedID[$id] = true;

				// Create modifier if not exists
				if ($node->modifier === null) {
					$node->modifier = new Modifier;
				}

				$node->modifier->id = $id;
			}
		}

		// Set document title from first heading
		if ($this->title === null) {
			$this->title = trim(Texy\Helpers::extractText($headings[0]));
		}
	}


	/**
	 * Parses underlined heading.
	 * @param  array<?string>  $matches
	 * @param  array<?int>  $offsets
	 */
	public function parseUnderline(
		Texy\BlockParser $parser,
		array $matches,
		string $name,
		array $offsets,
	): Texy\Nodes\HeadingNode
	{
		[, $mContent, $mMod, $mLine] = $matches;
		$level = $this->levels[$mLine[0]];
		$contentOffset = $offsets[1] ?? $offsets[0];
		return new Texy\Nodes\HeadingNode(
			$this->texy->createInlineParser()->parse(trim($mContent), $contentOffset),
			$level,
			Texy\Nodes\HeadingNode::Underlined,
			Modifier::parse($mMod),
			new Position($offsets[0], strlen($matches[0])),
		);
	}


	/**
	 * Parses surrounded heading.
	 * @param  array<?string>  $matches
	 * @param  array<?int>  $offsets
	 */
	public function parseSurround(
		Texy\BlockParser $parser,
		array $matches,
		string $name,
		array $offsets,
	): Texy\Nodes\HeadingNode
	{
		[, $mLine, $mContent, $mMod] = $matches;
		$level = min(7, max(2, strlen($mLine)));
		$level = $this->moreMeansHigher ? 7 - $level : $level - 2;
		$mContent = rtrim($mContent, $mLine[0] . ' ');
		$contentOffset = $offsets[2] ?? $offsets[0];
		return new Texy\Nodes\HeadingNode(
			$this->texy->createInlineParser()->parse(trim($mContent), $contentOffset),
			$level,
			Texy\Nodes\HeadingNode::Surrounded,
			Modifier::parse($mMod),
			new Position($offsets[0], strlen($matches[0])),
		);
	}


	public function solve(Nodes\HeadingNode $node, Generator $generator): string
	{
		// HeadingNode->level already contains the final level (1-6) after HeadingModule processing
		$level = $node->level;
		$content = $generator->generateInlineContent($node->content);
		$attrs = $generator->generateModifierAttrs($node->modifier);
		$open = $this->texy->protect("<h{$level}{$attrs}>", $this->texy::CONTENT_BLOCK);
		$close = $this->texy->protect("</h{$level}>", $this->texy::CONTENT_BLOCK);
		/*$el = new Texy\HtmlElement('h' . $node->level, $generator->generateInlineContent($node->content));
		$generator->decorate($node->modifier, $el);
		return $el->toString($this->texy);*/
		return $open . $content . $close;
	}


	/**
	 * Collect all HeadingNode from AST (excluding those inside texysource sections).
	 * @return list<Texy\Nodes\HeadingNode>
	 */
	private function collectHeadings(Texy\Node $node, bool $skip = false): array
	{
		// Skip headings inside texysource sections
		if ($node instanceof Texy\Nodes\SectionNode && $node->type === 'texysource') {
			$skip = true;
		}

		$headings = [];

		if ($node instanceof Texy\Nodes\HeadingNode && !$skip) {
			$headings[] = $node;
		}

		foreach ($node->getNodes() as $child) {
			$headings = [...$headings, ...$this->collectHeadings($child, $skip)];
		}

		return $headings;
	}
}
