<?php

/**
 * Texy! universal text -> html converter
 * --------------------------------------
 *
 * This source file is subject to the GNU GPL license.
 *
 * @author     David Grudl aka -dgx- <dave@dgx.cz>
 * @link       http://texy.info/
 * @copyright  Copyright (c) 2004-2007 David Grudl
 * @license    GNU GENERAL PUBLIC LICENSE v2
 * @package    Texy
 * @category   Text
 * @version    $Revision$ $Date$
 */

// security - include texy.php, not this file
if (!defined('TEXY')) die();



/**
 * Heading module
 */
class TexyHeadingModule extends TexyModule
{
    const
        DYNAMIC = 1,  // auto-leveling
        FIXED =   2;  // fixed-leveling

    protected $default = array('heading/surrounded' => TRUE, 'heading/underlined' => TRUE);

    /** @var string  textual content of first heading */
    public $title;

    /** @var array  generated Table of Contents */
    public $TOC;

    /** @var bool  autogenerate ID */
    public $generateID = FALSE;

    /** @var string  prefix for autogenerated ID */
    public $idPrefix = 'toc-';

    /** @var int  level of top heading, 1..6 */
    public $top = 1;

    /** @var int  balancing mode */
    public $balancing = TexyHeadingModule::DYNAMIC;

    /** @var array  when $balancing = TexyHeadingModule::FIXED */
    public $levels = array(
        '#' => 0,  //  #  -->  $levels['#'] + $top = 0 + 1 = 1  --> <h1> ... </h1>
        '*' => 1,
        '=' => 2,
        '-' => 3,
    );


    /** @var array  used ID's */
    private $usedID;

    private $_rangeUnderline;
    private $_deltaUnderline;
    private $_rangeSurround;
    private $_deltaSurround;



    public function init()
    {
        $this->texy->registerBlockPattern(
            array($this, 'patternUnderline'),
            '#^(\S.*)'.TEXY_MODIFIER_H.'?\n'
          . '(\#|\*|\=|\-){3,}$#mU',
            'heading/underlined'
        );

        $this->texy->registerBlockPattern(
            array($this, 'patternSurround'),
            '#^((\#|\=){2,})(?!\\2)(.+)\\2*'.TEXY_MODIFIER_H.'?()$#mU',
            'heading/surrounded'
        );

        $this->_rangeUnderline = array(10, 0);
        $this->_rangeSurround = array(10, 0);
        $this->title = NULL;
        $this->TOC = $this->usedID = array();

        $foo = NULL; $this->_deltaUnderline = & $foo;
        $bar = NULL; $this->_deltaSurround = & $bar;
    }



    /**
     * Callback for:
     *
     *  Heading .(title)[class]{style}>
     *  -------------------------------
     *
     * @param TexyBlockParser
     * @param array      regexp matches
     * @param string     pattern name
     * @return TexyHtml|string|FALSE
     */
    public function patternUnderline($parser, $matches)
    {
        list(, $mContent, $mMod, $mLine) = $matches;
        //  $matches:
        //    [1] => ...
        //    [2] => .(title)[class]{style}<>
        //    [3] => ...

        $mod = new TexyModifier($mMod);
        $level = $this->levels[$mLine];

        // dynamic headings balancing
        $this->_rangeUnderline[0] = min($this->_rangeUnderline[0], $level);
        $this->_rangeUnderline[1] = max($this->_rangeUnderline[1], $level);
        $this->_deltaUnderline = -$this->_rangeUnderline[0];
        $this->_deltaSurround = -$this->_rangeSurround[0] +
            ($this->_rangeUnderline[1] ? ($this->_rangeUnderline[1] - $this->_rangeUnderline[0] + 1) : 0);

        // event wrapper
        if (is_callable(array($this->texy->handler, 'heading'))) {
            $res = $this->texy->handler->heading($parser, $level, $mContent, $mod, FALSE);
            if ($res !== NULL) return $res;
        }

        return $this->solve($level, $mContent, $mod, FALSE);
    }



    /**
     * Callback for:
     *
     *   ### Heading .(title)[class]{style}>
     *
     * @param TexyBlockParser
     * @param array      regexp matches
     * @param string     pattern name
     * @return TexyHtml|string|FALSE
     */
    public function patternSurround($parser, $matches)
    {
        list(, $mLine, , $mContent, $mMod) = $matches;
        //    [1] => ###
        //    [2] => ...
        //    [3] => .(title)[class]{style}<>

        $mod = new TexyModifier($mMod);
        $level = 7 - min(7, max(2, strlen($mLine)));

        // dynamic headings balancing
        $this->_rangeSurround[0] = min($this->_rangeSurround[0], $level);
        $this->_rangeSurround[1] = max($this->_rangeSurround[1], $level);
        $this->_deltaSurround  = -$this->_rangeSurround[0] +
            ($this->_rangeUnderline[1] ? ($this->_rangeUnderline[1] - $this->_rangeUnderline[0] + 1) : 0);

        // event wrapper
        if (is_callable(array($this->texy->handler, 'heading'))) {
            $res = $this->texy->handler->heading($parser, $level, $mContent, $mod, TRUE);
            if ($res !== NULL) return $res;
        }

        return $this->solve($level, $mContent, $mod, TRUE);
    }



    /**
     * Finish invocation
     *
     * @param int
     * @param string
     * @param TexyModifier
     * @param bool
     * @return TexyHtml
     */
    public function solve($level, $content, $mod, $isSurrounded)
    {
        $tx = $this->texy;
        $el = new TexyHeadingElement;
        $mod->decorate($tx, $el);
        $el->eXtra['level'] = $level;
        $el->eXtra['top'] = $this->top;
        if ($this->balancing === self::DYNAMIC) {
            if ($isSurrounded)
                $el->eXtra['deltaLevel'] = & $this->_deltaSurround;
            else
                $el->eXtra['deltaLevel'] = & $this->_deltaUnderline;
        } else {
            $el->eXtra['deltaLevel'] = 0;
        }
        $el->parseLine($tx, trim($content));

        // document title
        $title = Texy::wash($el->getContent());
        if ($this->title === NULL) $this->title = $title;

        // Table of Contents
        if ($this->generateID && empty($el->id)) {
            $el->id = strtolower(iconv('UTF-8', 'ASCII//TRANSLIT', $title));
            $el->id = str_replace(' ', '-', $el->id);
            $el->id = $this->idPrefix . preg_replace('#[^a-z0-9_-]#i', '', $el->id);
            $counter = '';
            if (isset($this->usedID[$el->id . $counter])) {
                $counter = 2;
                while (isset($this->usedID[$el->id . '-' . $counter])) $counter++;
                $el->id .= '-' . $counter;
            }
            $this->usedID[$el->id] = TRUE;
        }

        $TOC = array(
            'id' => isset($el->id) ? $el->id : NULL,
            'title' => $title,
            'level' => 0,
        );
        $this->TOC[] = & $TOC;
        $el->eXtra['TOC'] = & $TOC;

        return $el;
    }


} // TexyHeadingModule







/**
 * HTML ELEMENT H1-6
 */
class TexyHeadingElement extends TexyHtml
{
    public $elName = 'h?';


    public function startTag()
    {
        $level = $this->eXtra['level'] + $this->eXtra['deltaLevel'] + $this->eXtra['top'];
        $this->elName = 'h' . min(6, max(1, $level));
        $this->eXtra['TOC']['level'] = $level;
        return parent::startTag();
    }

} // TexyHeadingElement
